#pragma once

#include "rclcpp/rclcpp.hpp"
#include "behaviortree_cpp/behavior_tree.h"
#include "sonia_bt_runner/utils/SlalomPointArray.hpp"
#include "sonia_bt_runner/utils/Trajectory.hpp"

#define COMPUTE_SLALOM_GATE_TRAJECTORY_POINTS "Points"
#define COMPUTE_SLALOM_GATE_TRAJECTORY_POINTS_TYPE SlalomPointArray

#define COMPUTE_SLALOM_GATE_TRAJECTORY_SIDE "Side"
#define COMPUTE_SLALOM_GATE_TRAJECTORY_SIDE_TYPE std::string

#define COMPUTE_SLALOM_GATE_TRAJECTORY_CLUSTER_TOLERANCE "ClusterTolerance"
#define COMPUTE_SLALOM_GATE_TRAJECTORY_CLUSTER_TOLERANCE_PARAMS COMPUTE_SLALOM_GATE_TRAJECTORY_CLUSTER_TOLERANCE, 0.7f, "Maximum distance in meters between two points of the same pipe"
#define COMPUTE_SLALOM_GATE_TRAJECTORY_CLUSTER_TOLERANCE_TYPE float

#define COMPUTE_SLALOM_GATE_TRAJECTORY_MIN_POINTS_PER_CLUSTER "MinPointsPerCluster"
#define COMPUTE_SLALOM_GATE_TRAJECTORY_MIN_POINTS_PER_CLUSTER_PARAMS COMPUTE_SLALOM_GATE_TRAJECTORY_MIN_POINTS_PER_CLUSTER, 3, "Minimum number of points for a cluster to count as a pipe"
#define COMPUTE_SLALOM_GATE_TRAJECTORY_MIN_POINTS_PER_CLUSTER_TYPE int

#define COMPUTE_SLALOM_GATE_TRAJECTORY_MAX_GATE_RANGE "MaxGateRange"
#define COMPUTE_SLALOM_GATE_TRAJECTORY_MAX_GATE_RANGE_PARAMS COMPUTE_SLALOM_GATE_TRAJECTORY_MAX_GATE_RANGE, 10.0f, "Pipes further than this distance in meters are ignored"
#define COMPUTE_SLALOM_GATE_TRAJECTORY_MAX_GATE_RANGE_TYPE float

#define COMPUTE_SLALOM_GATE_TRAJECTORY_APPROACH_STANDOFF "ApproachStandoff"
#define COMPUTE_SLALOM_GATE_TRAJECTORY_APPROACH_STANDOFF_PARAMS COMPUTE_SLALOM_GATE_TRAJECTORY_APPROACH_STANDOFF, 1.0f, "Distance in meters before the gap where the sub stops to align itself"
#define COMPUTE_SLALOM_GATE_TRAJECTORY_APPROACH_STANDOFF_TYPE float

#define COMPUTE_SLALOM_GATE_TRAJECTORY_PASS_DISTANCE "PassDistance"
#define COMPUTE_SLALOM_GATE_TRAJECTORY_PASS_DISTANCE_PARAMS COMPUTE_SLALOM_GATE_TRAJECTORY_PASS_DISTANCE, 2.0f, "Forward distance in meters to travel after the gap"
#define COMPUTE_SLALOM_GATE_TRAJECTORY_PASS_DISTANCE_TYPE float

#define COMPUTE_SLALOM_GATE_TRAJECTORY_GATE_HEADING "GateHeading"
#define COMPUTE_SLALOM_GATE_TRAJECTORY_GATE_HEADING_TYPE float

#define COMPUTE_SLALOM_GATE_TRAJECTORY_TRAJECTORY "Trajectory"
#define COMPUTE_SLALOM_GATE_TRAJECTORY_TRAJECTORY_TYPE Trajectory

namespace navigation {

class ComputeSlalomGateTrajectory : public BT::SyncActionNode {
public:
    ComputeSlalomGateTrajectory(const std::string &name, const BT::NodeConfig &config, std::shared_ptr<rclcpp::Node> node);
    ~ComputeSlalomGateTrajectory() override = default;

    static BT::PortsList providedPorts() {
        return {
            BT::InputPort<COMPUTE_SLALOM_GATE_TRAJECTORY_POINTS_TYPE>(COMPUTE_SLALOM_GATE_TRAJECTORY_POINTS),
            BT::InputPort<COMPUTE_SLALOM_GATE_TRAJECTORY_SIDE_TYPE>(COMPUTE_SLALOM_GATE_TRAJECTORY_SIDE),
            BT::InputPort<COMPUTE_SLALOM_GATE_TRAJECTORY_CLUSTER_TOLERANCE_TYPE>(COMPUTE_SLALOM_GATE_TRAJECTORY_CLUSTER_TOLERANCE_PARAMS),
            BT::InputPort<COMPUTE_SLALOM_GATE_TRAJECTORY_MIN_POINTS_PER_CLUSTER_TYPE>(COMPUTE_SLALOM_GATE_TRAJECTORY_MIN_POINTS_PER_CLUSTER_PARAMS),
            BT::InputPort<COMPUTE_SLALOM_GATE_TRAJECTORY_MAX_GATE_RANGE_TYPE>(COMPUTE_SLALOM_GATE_TRAJECTORY_MAX_GATE_RANGE_PARAMS),
            BT::InputPort<COMPUTE_SLALOM_GATE_TRAJECTORY_APPROACH_STANDOFF_TYPE>(COMPUTE_SLALOM_GATE_TRAJECTORY_APPROACH_STANDOFF_PARAMS),
            BT::InputPort<COMPUTE_SLALOM_GATE_TRAJECTORY_PASS_DISTANCE_TYPE>(COMPUTE_SLALOM_GATE_TRAJECTORY_PASS_DISTANCE_PARAMS),
            BT::OutputPort<COMPUTE_SLALOM_GATE_TRAJECTORY_GATE_HEADING_TYPE>(COMPUTE_SLALOM_GATE_TRAJECTORY_GATE_HEADING),
            BT::BidirectionalPort<COMPUTE_SLALOM_GATE_TRAJECTORY_TRAJECTORY_TYPE>(COMPUTE_SLALOM_GATE_TRAJECTORY_TRAJECTORY),
        };
    }

    BT::NodeStatus tick() override;

private:
    std::shared_ptr<rclcpp::Node> _ros_node;
};

}  // namespace navigation
