#pragma once

#include "rclcpp/rclcpp.hpp"
#include "behaviortree_cpp/behavior_tree.h"
#include "sonia_bt_runner/utils/AiDetection.hpp"
#include "sonia_bt_runner/utils/Trajectory.hpp"

#define COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_DETECTION_A "DetectionA"
#define COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_DETECTION_A_TYPE AiDetection

#define COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_DETECTION_B "DetectionB"
#define COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_DETECTION_B_TYPE AiDetection

#define COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_POSITION_X "PositionX"
#define COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_POSITION_X_PARAMS COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_POSITION_X, 10.0f, "Forward distance to travel after centering between the two detections"
#define COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_POSITION_X_TYPE float

#define COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_SIDE "Side"
#define COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_SIDE_TYPE std::string

#define COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_DETECTION_ANGLE "Angle"
#define COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_DETECTION_ANGLE_TYPE float

#define COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_OFFSET_ANGLE "OffsetAngle"
#define COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_OFFSET_ANGLE_PARAMS "The angle that the sub rotate to maximum to search the white slalom"
#define COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_OFFSET_ANGLE_TYPE float

#define COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_TRAJECTORY "Trajectory"
#define COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_TRAJECTORY_TYPE Trajectory

namespace navigation {

class ComputeTrajectoryBetweenDetections : public BT::SyncActionNode {
public:
    ComputeTrajectoryBetweenDetections(const std::string &name, const BT::NodeConfig &config, std::shared_ptr<rclcpp::Node> node);
    ~ComputeTrajectoryBetweenDetections() override = default;

    static BT::PortsList providedPorts() {
        return {
            BT::InputPort<COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_DETECTION_A_TYPE>(COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_DETECTION_A),
            BT::InputPort<COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_DETECTION_B_TYPE>(COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_DETECTION_B),
            BT::InputPort<COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_POSITION_X_TYPE>(COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_POSITION_X_PARAMS),
            BT::InputPort<COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_SIDE_TYPE>(COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_SIDE),
            BT::InputPort<COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_DETECTION_ANGLE_TYPE>(COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_DETECTION_ANGLE),
            BT::InputPort<COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_OFFSET_ANGLE_TYPE>(COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_OFFSET_ANGLE),
            BT::BidirectionalPort<COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_TRAJECTORY_TYPE>(COMPUTE_TRAJECTORY_BETWEEN_DETECTIONS_TRAJECTORY),
        };
    }

    BT::NodeStatus tick() override;

private:
    std::shared_ptr<rclcpp::Node> _ros_node;
};

}  // namespace navigation
